//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Kollisionsregel
    {
        public int Kollisionsregel_ID { get; set; }
        public string Department__ID_One { get; set; }
        public string Exanmine_ID_One { get; set; }
        public string Department_ID_Two { get; set; }
        public string Exanmine_ID_Two { get; set; }
        public string Kollisionsregel_Tyoe { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
