//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CheckQueue
    {
        public string Department { get; set; }
        public string Examine { get; set; }
        public string Examine_Place { get; set; }
        public string Examine_Period { get; set; }
        public string Examine_Date { get; set; }
        public string Patient_ID { get; set; }
    }
}
