//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_AgeRules
    {
        public int AgeRules_ID { get; set; }
        public int Department_ID { get; set; }
        public int Examine_ID { get; set; }
        public int MinAge { get; set; }
        public int MaxAge { get; set; }
        public string AgeUnit { get; set; }
        public bool Enabled { get; set; }
        public bool Deleted { get; set; }
    }
}
