//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_NumberTimes_Now
    {
        public int Department_ID { get; set; }
        public int Examine_ID { get; set; }
        public int CheckNumber { get; set; }
        public string Period { get; set; }
        public int Period_No { get; set; }
        public int ID { get; set; }
    }
}
