//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Reservations
    {
        public int ReservationId { get; set; }
        public string ReservationData { get; set; }
        public string StudyKindName { get; set; }
        public Nullable<int> SystemType { get; set; }
        public Nullable<System.DateTime> ReserveBeginTime { get; set; }
        public Nullable<System.DateTime> ReserveEndTime { get; set; }
        public string ReserveState { get; set; }
        public Nullable<int> IsCharged { get; set; }
        public string ReserveOperator { get; set; }
        public string ReserveDepartment { get; set; }
        public Nullable<System.DateTime> SaveTime { get; set; }
        public string StudyDepartmentPlace { get; set; }
        public string ScanType { get; set; }
        public string ReserveDepartmentStudySource { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> RequestId { get; set; }
    
        public virtual MAS_Patient MAS_Patient { get; set; }
        public virtual MAS_Request MAS_Request { get; set; }
    }
}
