//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_NumberTimes_Scheme
    {
        public int Schemes_ID { get; set; }
        public int Department_ID { get; set; }
        public int Eanmine_ID { get; set; }
        public System.DateTime Am_StartTime { get; set; }
        public System.DateTime Am_EndTime { get; set; }
        public System.DateTime Pm_StartTime { get; set; }
        public System.DateTime Pm_EndTime { get; set; }
        public int Period { get; set; }
        public int Mins { get; set; }
        public int OfficeNumber { get; set; }
        public int CheckNumber { get; set; }
        public string EffectiveDate { get; set; }
        public int DateType_ID { get; set; }
        public bool Deleted { get; set; }
    }
}
