//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MASEntities : DbContext
    {
        public MASEntities()
            : base("name=MASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAS_Actions> MAS_Actions { get; set; }
        public virtual DbSet<MAS_AgeRules> MAS_AgeRules { get; set; }
        public virtual DbSet<MAS_DateType> MAS_DateType { get; set; }
        public virtual DbSet<MAS_Department> MAS_Department { get; set; }
        public virtual DbSet<MAS_ExaminePlace> MAS_ExaminePlace { get; set; }
        public virtual DbSet<MAS_ExamineType> MAS_ExamineType { get; set; }
        public virtual DbSet<MAS_Kollisionsregel> MAS_Kollisionsregel { get; set; }
        public virtual DbSet<MAS_NumberTimes_Now> MAS_NumberTimes_Now { get; set; }
        public virtual DbSet<MAS_NumberTimes_Queue> MAS_NumberTimes_Queue { get; set; }
        public virtual DbSet<MAS_NumberTimes_Scheme> MAS_NumberTimes_Scheme { get; set; }
        public virtual DbSet<MAS_Patient> MAS_Patient { get; set; }
        public virtual DbSet<MAS_Request> MAS_Request { get; set; }
        public virtual DbSet<MAS_Reservations> MAS_Reservations { get; set; }
        public virtual DbSet<MAS_RoleActions> MAS_RoleActions { get; set; }
        public virtual DbSet<MAS_Roles> MAS_Roles { get; set; }
        public virtual DbSet<MAS_UserRoles> MAS_UserRoles { get; set; }
        public virtual DbSet<MAS_Users> MAS_Users { get; set; }
        public virtual DbSet<MAS_CheckQueue> MAS_CheckQueue { get; set; }
    }
}
